
version: 2

sources:
  - name: OnlineRetail
    database: OnlineRetail  
    schema: public

models:
  - name: product_views_analysis_dbt_model
    description: "A data model for product views analysis"
    columns:
      - name: date_id
        description: "date_id in the format of YYYYMMDD; integer"
        data_tests:
          - not_null
      - name: category
        description: "product_category"
        data_tests:
          - not_null
      - name: product_id
        description: "product"
        data_tests:
          - not_null
      - name: total_views
        description: "The number of times the product was viewed on the day"
        data_tests:
          - not_null

